### ISSUE TITLE
throwing error message 

### ISSUE THREAD

**Issue by sachinsky** [acharrex/magento2-extension-ajax-pagination-sorting#5]
After installation and configuration its not working just appearing popup and ajax got abort getting Sorry, ......... is there any file which is missing,

**Comment by shopigo** [comment]
Hi,
Can you post a screenshot of your browser's console ? (after the error occurred)

**Comment by shopigo** [comment]
Can you go to http://magento223.local/women/tops-women.html?product_list_mode=list&ajax=1 and post the content returned by Magento ?

Are you using Magento 2.2.3 ?
Are you using custom extensions ?

**Comment by sachinsky** [comment]
After hitting this url http://magento223.local/women/tops-women.html?product_list_mode=list&ajax=1 getting correct output but if loading through ajax the url update doesn't work.

I am not using any extensions or custom extension

Yes using magento2.2.3

Can you please share this with updated extension for this of which you are currently using it. 

Thanks in advance

**Comment by sachinsky** [comment]
![screenshot from 2019-01-24 11-55-29](https://user-images.githubusercontent.com/8760695/51659876-e9a45e00-1fd1-11e9-95f8-cb4b1c71c61e.png)

**Comment by shopigo** [comment]
When a category page is loaded with the parameter "ajax=1" its output should be a JSON.

Is the Shopigo AJAX Listing extension enabled ? (cf. https://github.com/shopigo/magento2-extension-ajax-listing)

**Comment by sachinsky** [comment]
I am using this https://github.com/shopigo/magento2-extension-ajax-pagination-sorting instead have not installed this  https://github.com/shopigo/magento2-extension-ajax-listing

**Comment by shopigo** [comment]
Yes, but as documented here https://github.com/shopigo/magento2-extension-ajax-pagination-sorting#method-2---installing-using-archive, the AJAX Pagination and Sorting extension requires the AJAX Listing extension.

Try to install and enable the AJAX Listing extension.
